### PR TITLE
Fix incorect template path

### PR DESCRIPTION
**Pull request by sadortun**

### CODE REVIEW

**Comment by anyt** [comment]
Hi @sadortun,

Please explain why the path is incorrect?
Without these changes, different templates for different widget types, like dialog, were selected automatically. But now it doesn't work.

**Comment by sadortun** [comment]
Hi @anything

First it seems this controller is not used from any oro code. ( searching by route name) 

Also for the controller to find the path automatically it need to be under

Ressources/views/Grid/widget.html.twig

But the file is currently under

Ressources/views/Grid/widget/widget.html.twig

Can you please explain how the following works ? 
> Without these changes, different templates for different widget types, like dialog, were selected automatically

**Comment by vtsykun** [comment]
Hi @sadortun 
> Also for the controller to find the path automatically it need to be under

There is exist listener in [UIBundle](https://github.com/oroinc/platform/blob/3.1/src/Oro/Bundle/UIBundle/EventListener/TemplateListener.php#L39) to select different templates for different widget types.
For example
1) https://demo.orocrm.com/index.php/datagrid/widget/users-grid?_widgetContainer=dialog - render grid for [dialog widget](https://github.com/oroinc/platform/blob/3.1/src/Oro/Bundle/DataGridBundle/Resources/views/Grid/dialog/widget.html.twig)
2) https://demo.orocrm.com/index.php/datagrid/widget/users-grid?_widgetContainer=block - render [default grid template](https://github.com/oroinc/platform/blob/3.1/src/Oro/Bundle/DataGridBundle/Resources/views/Grid/dialog/widget.html.twig)

If you need to load the grid with ajax, you can add get parameter `_widgetContainer=block` into request

**Comment by anyt** [comment]
I'm closing the PR as there is nothing wrong with the template path.
Thank you!

**Comment by sadortun** [comment]
@vtsykun Awesome, thanks for the details !

**Pull request closed without merging**
