### PR TITLE
Fix incorrect namespace for UpdateEnumEntityTranslations

### PR DESCRIPTION
**Pull request by ibastiaansewebmen**
Currently this class cannot be autoloaded, this PR should make that possible again.

### CODE REVIEW

**Comment by rskuipers** [comment]
I ran into this issue as well, thank you for fixing @ibastiaansewebmen! :+1:

**Comment by anyt** [comment]
Hi everyone,

Thank you, @ibastiaansewebmen, for your contribution!

Can you please, share how you have found this issue? 
Because our CI and local development setups haven't detected it, and we need to find this kind of issue before publishing.

**Comment by ibastiaansewebmen** [comment]
Hi @anyt 

In one of our projects we made a translation migration and added this class as a dependency. In our CI we have phpstan running and this tried to find the class but couldn't find it because the namespace is not the same as the directory structure. Hope you have enough info for now.

**Comment by anyt** [comment]
Yes, it's enough. We already use phpstan for [SQL injections check](https://github.com/oroinc/phpstan-rules), so it shouldn't be hard to add one more rule there. 

We'll take a look, thank you!

**Comment by anyt** [comment]
Merged, https://github.com/oroinc/platform/commit/48b4ec952e3f23a02187038c0799506a7d2028f7. 
Thank you for your contribution, @ibastiaansewebmen!

**Pull request closed without merging**
