### PR TITLE
Supervisor program name must be unique

### PR DESCRIPTION
**Pull request by cmourizard**
Add a mention about that the program name set un the supervisor definition must be unique if you have multiple instances on the same supervisord server.

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by cmourizard** [comment]
I filled the CLA, do I need to perform some other tasks?

**Comment by mbessolov** [comment]
The robot will check the signatures and update PR in a few hours.
Thank you for the contribution.

**Comment by cmourizard** [comment]
👍

**Comment by anyt** [comment]
Thank you for your contribution!
The PR was merged. Changes from it will be synced to the public repository in a few days.

**Comment by anyt** [comment]
Merged to master https://github.com/oroinc/platform/commit/bd0cf56c2590b3a346479198f3271034594255d1.
Thank you

**Pull request closed without merging**
