### PR TITLE
Allow users to extract separately 'Month', 'Year' and 'Day of Year' from date/datetime columns in Oro Reports

### PR DESCRIPTION
**Pull request by pedrofurtado**

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by pedrofurtado** [comment]
What do you guys think about this PR? It comes from a need here of users to extract some numeric informations about a date/datetime column in Oro Reports. Because of that, I thought that this feature could be great also for the community, because this kind of feature is commonly used in another systems.

Thanks!

**Comment by anyt** [comment]
Hi @pedrofurtado,

Thank you for contribution! The feature should be useful for community.
But I can't accept the PR as, unfortunately, you have not signed our Contributor License Agreement.

**Comment by pedrofurtado** [comment]
@anyt Thanks for feedback! I will sign in to CLA.

**Comment by pedrofurtado** [comment]
@anyt I am signed in CLA now :+1:

capturar

**Comment by pedrofurtado** [comment]
@anyt Is this PR ready for merge?

**Comment by pedrofurtado** [comment]
@anyt Thanks, man!

**Comment by anyt** [comment]
Merged to master branch.

Thank you.

**Pull request closed without merging**
