### PR TITLE
Add empty/not empty to dictionary conditions in segment/report

### PR DESCRIPTION
**Pull request by vtsykun**
The PR to be able to use "is empty" and "is not empty" conditions when using dictionary filter in reports or segment. Currently only "is any of" and "is not any of" is available.
Selection_999(210)

### CODE REVIEW

**Comment by mbessolov** [comment]
_Internal reference - BAP-18600_

**Comment by mbessolov** [comment]
@vtsykun there are a few code style problems in this PR:

```
09:40:55 FILE: ...ro/Bundle/FilterBundle/Form/Type/Filter/DictionaryFilterType.php
09:40:55  ----------------------------------------------------------------------
09:40:55  FOUND 1 ERROR AFFECTING 1 LINE
09:40:55  ----------------------------------------------------------------------
09:40:55   15 | ERROR | Missing doc comment for class DictionaryFilterType
09:40:55  ----------------------------------------------------------------------
09:40:55  
09:40:55  FILE: ...latform/src/Oro/Bundle/TagBundle/Filter/TagsDictionaryFilter.php
09:40:55  ----------------------------------------------------------------------
09:40:55  FOUND 1 ERROR AFFECTING 1 LINE
09:40:55  ----------------------------------------------------------------------
09:40:55   100 | ERROR | [x] CASE keyword must be followed by a single space
09:40:55  ----------------------------------------------------------------------
```
This is the set of rules that we use - https://github.com/oroinc/platform/blob/master/build/Oro/phpcs.xml

**Comment by vtsykun** [comment]
Fixed CS

**Comment by anyt** [comment]
Merged, 
Thank you for the contribution, @vtsykun!

**Pull request closed without merging**
