### PR TITLE
Fix CountQueryBuilderOptimizer generate a wrong query

### LINKED ISSUE #778: [BatchBundle] CountQueryBuilderOptimizer generate a wrong query
Step to reproduce
1) Branch 2.3 oro/crm oro/platform
2) Create datagrid with configuration that contains filter for relations `ManyToOne -> OneToMany -> ManyToOne`
Example of datagrid  - update cases-grid `Case->Contact->primaryAddress->region->name`. using the [patch](https://patch-diff.githubusercontent.com/raw/vtsykun/crm/pull/1.diff) 
```patch
diff --git a/src/Oro/Bundle/CaseBundle/Resources/config/oro/datagrids.yml b/src/Oro/Bundle/CaseBundle/Resources/config/oro/datagrids.yml
index 4b1c6c812f..2ee60f2ce3 100644
--- a/src/Oro/Bundle/CaseBundle/Resources/config/oro/datagrids.yml
+++ b/src/Oro/Bundle/CaseBundle/Resources/config/oro/datagrids.yml
@@ -170,6 +170,23 @@ datagrids:
                 link:         delete_link
     cases-grid:
         extends: base-case-grid
+        source:
+            query:
+                select:
+                    - contactRegion.name as contactRegionName
+                join:
+                    left:
+                        -
+                            join: relatedContact.addresses
+                            alias: contactAddress
+                            conditionType: WITH
+                            condition: "contactAddress.primary = true"
+                        -
+                            join: contactAddress.region
+                            alias: contactRegion
+        columns:
+            contactRegionName:
+                label: contactRegionName
         filters:
             columns:
                 relatedContact:
@@ -182,6 +199,10 @@ datagrids:
                     type: string
                     data_name: relatedAccountName
                     enabled: false
+                contactRegion:
+                    label: contactRegionName
+                    type: string
+                    data_name: contactRegionName
         options:
             entity_pagination: true
     account-cases-grid:
@@ -321,3 +342,4 @@ datagrids:
                         field_options:
                             class: OroCaseBundle:CasePriority
                             property: label
+
```
3) Go to cases index page and apply new filter
selection_149
4)An error occurred during apply filter
selection_148

### PR DESCRIPTION
**Pull request by vtsykun**
- Fixed #778 
- Added failed tests

### CODE REVIEW

**Comment by manowark** [comment]
Hello, @vtsykun.

Would you please sign our Contributor License Agreement? (https://www.orocrm.com/contributor-license-agreement) Thank you!

**Comment by vtsykun** [comment]
"Would you please sign our Contributor License Agreement?"
Done

**Comment by EugeneC** [comment]
Thank you for the proposed bug fix.
Internal ID: BAP-16357.

**Comment by EugeneC** [comment]
I have merged this PR to the master branch. Thank you!

**Pull request closed without merging**
