### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by aistis-**
Reopened from https://github.com/oroinc/OroMessageQueueComponent/pull/1

P.S. You should consider disabling PR on subsplit repos :)

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by ishirko** [comment]
Hello, @aistis- .
Thank you for your report.
Created an internal task to fix the problem (id: BAP-15766).

**Comment by aistis-** [comment]
Hi, isn't it enough just to accept the PR? :)

**Comment by manowark** [comment]
Hello, @aistis-. It is enough, but in accordance with our flow of merging PR - we should do few other activities. After that your PR will be available in master.
If you have more questions fell free to ask.

**Comment by manowark** [comment]
Your PR has been merged. Changes from PR will be synced to the public repository in a few days. Thank you.

**Pull request closed without merging**
