### PR TITLE
Adding database version to configs

### PR DESCRIPTION
**Pull request by easybi-mv**
Adding database server version to doctrine configs to prevent eager DB connection (required in case of stateless commands for building assets)

### CODE REVIEW

**Comment by anyt** [comment]
Hi @easybi-mv,
Thank you for your contribution. 
Please provide steps to reproduce the issue, to understand your use case better.

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://oroinc.com/b2b-ecommerce/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by anyt** [comment]
There is no need to provide the version per connection.

You can achieve the same without patching vendors, but by specifying the server version in `config/config.yml` file in the application level.
```yaml
doctrine:
     dbal:
         server_version: '5.7'
```

**Comment by easybi-mv** [comment]
>   [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                    
>   Unrecognized option "server_version" under "doctrine.dbal". Available options are "connections", "default_connection", "types".  
> 
>

**Comment by anyt** [comment]
Which version of doctrine/dbal do you have in a project?
For me, it works on `v2.7.2`

To know the doctrine/dbal version you can use below command
```bash
composer info doctrine/dbal  | grep versions
```

**Comment by anyt** [comment]
Nevertheless, even in an older version, you can extend or override the configuration from the bundle's `app.yml` in  `config/config.yml` file.

**Comment by easybi-mv** [comment]
Stange, we are also on 2.7.2 and we use ORO 4.1.*. We also extended the doctrine config in config.yml for all connections :smile: 
It would be nice to have this as part of original bundle configs if anyone encounters similar problems.
Now we only need to speed up/resolve webpack build time. Thank you for suggestions!

**Comment by echantigny** [comment]
@easybi-mv @anyt  Hi!  I'm running into this exact same issue and I am not able to get it to run.  I've added server_version to my config.yml without any results

`doctrine:
    dbal:
        server_version: mariadb-10.4.14`

I clear the cache folder and run the `php bin/console oro:assets:install --env=prod` again but I always get the `An exception occured while establishing a connection to figure out your platform version.  You can circumvent this by setting a 'server_version' configuration value `

Any ideas on how to get this up and running?

**Comment by anyt** [comment]
Hi @echantigny ,
The error happens when the application can not connect to the database. So, first of all, you should check the connection credentials in the config/parameters.yml file. Also, the error stack trace should have the original exception message from the database driver, like 
```
SQLSTATE[08006] [7] FATAL:  remaining connection slots are reserved for non-replication superuser
```
or 
```
SQLSTATE[08006] [7] timeout expired at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50, 
```
or
```
SQLSTATE[08006] [7] could not connect to server: Connection refused
```
etc.

**Comment by echantigny** [comment]
@anyt That's exactly it, my database is not up because I'm trying to build the assets in my image, with no connection to the database, as the original poster mentionned.  I am able to run `php bin/console oro:assets:install` but not `php bin/console oro:assets:install --env=prod`


```
In OroEntityExtendBundle.php line 121:
                                                                                   
  In ConnectionFactory.php line 87:                                                
                                                                                   
    An exception occured while establishing a connection to figure out your pla    
    tform version.                                                                 
    You can circumvent this by setting a 'server_version' configuration value      
                                                                                   
    For further information have a look at:                                        
    https://github.com/doctrine/DoctrineBundle/issues/673                          
                                                                                   
                                                                                   
  In AbstractMySQLDriver.php line 112:                                             
                                                                                   
    An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir    
    ectory                                                                         
                                                                                   
                                                                                   
  In PDOConnection.php line 50:                                                    
                                                                                   
    SQLSTATE[HY000] [2002] No such file or directory                               
                                                                                   
                                                                                   
  In PDOConnection.php line 46:                                                    
                                                                                   
    SQLSTATE[HY000] [2002] No such file or directory   
```

**Comment by anyt** [comment]
A similar parameter was introduced in the scope of https://github.com/oroinc/platform/commit/399b6e3bb7df3d3b066c2c077a0b5b7ff3f69609.
Thank you for your contribution, @easybi-mv.

**Pull request closed without merging**
