### PR TITLE
Allow users to create DISTINCT functions for aggregation SQL operators (COUNT, SUM, AVG) in Oro Reports

### LINKED ISSUE #825: Allow users to create DISTINCT functions for aggregation SQL operators (COUNT, SUM, AVG) in Oro Reports
I've created a pull request that allows users to create DISTINCT functions for aggregation SQL operators (COUNT, SUM, AVG) in Oro Reports.

It's deeply based on this question in OroCRM Forum: https://oroinc.com/orocrm/forums/topic/create-custom-function-in-orocrm-reports

### PR DESCRIPTION
**Pull request by pedrofurtado**
Allow users to create DISTINCT functions for aggregation SQL operators (COUNT, SUM, AVG) in Oro Reports. 

It's a very simple pull request, that adds a very great feature for all community that create simple and advanced reports in Oro.

It's deeply based on this question in OroCRM Forum: https://oroinc.com/orocrm/forums/topic/create-custom-function-in-orocrm-reports

Closes #825

### CODE REVIEW

**Comment by pedrofurtado** [comment]
The scrutinizer CI fails because of a fault on disk or memory space, not related with the code of pull request. Please, check it.
capturar

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by vsoroka** [comment]
Hello @pedrofurtado,

could you please describe a couple of real reports for which COUNT/SUM/AVG with DISTINCT can be useful?

Thank you.

**Comment by pedrofurtado** [comment]
@vsoroka 

An example:

```
Table category(ID, Name)
                ↑------------↓
Table products(ID, Name, categoryID)
```
Supose I want to know how many different categories it is currently related to all products.

The SQL I want to execute is something like this below:

```sql
SELECT COUNT(DISTINCT categoryID) AS quantity_of_different_categories_related_to_the_products
FROM products;
```

Depending of the number returned by this SQL query, I will know how deep is the granularity of the categories.
A small number indicates that the categories are so much generic OR just a little part of categories have been used for relationship. A big number indicates the possibility of duplicated categories or irrelevant categories (that can be joined into only one category).

It's a simple example that this feature is so useful. Just use our imagination to some other complex situation like this. This kind of SQL query is so much common as we can think.

Provide it already inside OroPlatform core is a good improvement.

**Comment by pedrofurtado** [comment]
@vsoroka @mbessolov Any news about this pull request? Is it ready for merge?

**Comment by mbessolov** [comment]
@pedrofurtado  While it is definitely an interesting feature, we should consider possible performance implications. We have customers who use Oro products with tens of millions of records. What will happen if the products table from your example contains 1 million records, 10 millions records, or even more? How much performance testing and what datasets have you performed?

Unless accompanied by a lot of scaffoliding and safeguards that would not allow a user to use these functions in a report that involves large tables, I do not think it can be accepted into the core product yet.
The best way to proceed may be to create and publish a separate bundle to provide this kind of aggregation functions for the reports - and this bundle can be used by developers who are willing to take the risk or train their customers when not to use it.

**Comment by pedrofurtado** [comment]
@mbessolov Thanks for feedback!

I'm not sure if there is something that we can do about performance. Any aggregation function (with DISTINCT or without) is naturally expensive. The way to deal with this is creating indexes, auxiliar tables with summarized data, or something like this. Anyway, I don't believe that aggregation function with DISTINCT miss so much in performance and justify to be not feasible to merge.

Thanks!

**Comment by sadortun** [comment]
@mbessolov This is a very interesting PR.  I've done performance testing,  Comparing similar queries with `COUNT()` and `COUNT(DISTINCT)`  on tables with 16million rows,   

There is only a 2X slower that regular count queries.


 Showing rows 0 - 49 (16325229 total, Query took 0.3224 seconds.)
```sql
SELECT count(item_id) FROM `table` WHERE 1
```

 Showing rows 0 - 49 (16325229 total, Query took 0.7234 seconds.)
```sql
SELECT count(DISTINCT item_id) FROM `table` WHERE 1
```

**Comment by pedrofurtado** [comment]
@mbessolov @vsoroka @sadortun I am signed in CLA now :+1:

**Comment by pedrofurtado** [comment]
@mbessolov @vsoroka @sadortun Any news? 🤔

**Comment by anyt** [comment]
Hi @pedrofurtado,
Did you do any performance testing on real data?
Results that @sadortun posted above can't be accepted as they are not related to real cases with several joins, sorting and grouping. 

Here are first 2 links from Google related to the performance problem @mbessolov mentioned.
https://stackoverflow.com/questions/29076679/optimizing-countdistinct-slowness-even-with-covering-indexes
In this question, the difference is huge, the query with distinct took 50 seconds, without - 1.5s. This is not acceptable for rendering reports.
https://www.periscopedata.com/blog/use-subqueries-to-count-distinct-50x-faster
query without distinct 50 times faster.


Did you consider an option to create the separate extension and support it by yourself, as @mbessolov mentioned before?

**Comment by pedrofurtado** [comment]
@sadortun @anyt Sorry for long time without feedback. Well, here in company we have 2 instances of OroCRM with, approximately, 50-60 millions of records including entities like Tasks, Events, Contacts, Accounts and so on (and increasing). There are only some few pages that suffers with delay. One of them is the `/account` route (page that list all Accounts from system), because of many relationships that this Entity has.
But in Reports, we use a lot the feature of this PR (with this exactly code), and we have a great performance, and a great feature, used a lot by users. It would be interesting if it was included by default (out of box) with a fresh installation of OroCRM, in order to provide to community one more option of functions. In addition to bringing an improvement of the Reports, performance is not impaired (at least here in company).

Thanks!

**Pull request closed without merging**
